const fs = require('node:fs');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const ts = require('typescript');
const transpile = source => ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const helpers = {exports:{}};
vm.runInNewContext(transpile(fs.readFileSync('app/lib/legacyHoldPoints.ts','utf8')), helpers);
const {isLegacyHoldPoint,legacyHoldPointToRecord,legacyHoldPointToRow,isMissingHoldPointsTable}=helpers.exports;
const point = {id:'point',projectId:'project-a',serialNo:3,referenceNo:'HP3',name:'יציקה',structureNodeId:'node',element:'קיר',status:'נוצרה, לא הושלמה',checklistIds:['check'],nonconformanceIds:[],trialSectionIds:['trial'],documents:[{name:'photo.jpg',dataUrl:'data:image/jpeg;base64,abc'}],qcCompany:'QC',qaCompany:'QA',notes:'original notes',createdBy:'editor',createdAt:'2026-08-01T12:00:00Z',updatedAt:'2026-08-02T12:00:00Z',releasedAt:''};
const row=legacyHoldPointToRow(point);
assert.deepEqual(JSON.parse(JSON.stringify(legacyHoldPointToRecord(row))),point);
assert.equal(isLegacyHoldPoint({title:'דוח בנושא נקודת עצירה'}),false,'A genuine report may mention hold points');
assert.equal(legacyHoldPointToRecord({title:'דוח פיקוח',notes:JSON.stringify(point)}),null);
assert.equal(legacyHoldPointToRecord({...row,notes:'invalid json'}).name,'יציקה');
assert.equal(legacyHoldPointToRecord({...row,project_id:'project-b'}).projectId,'project-b','Database project identity takes priority');
assert.equal(isMissingHoldPointsTable({code:'42501',message:'hold_points denied'}),false,'Do not mask permissions errors');
const source=fs.readFileSync('app/page.tsx','utf8');
const ast=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const wanted=['loadProjectHoldPoints','normalizeSupervisionReport','supervisionReportRowToRecord','SUPERVISION_REPORT_STATUS_OPTIONS'];
const snippets=ast.statements.filter(n=>wanted.includes(n.name?.text)||ts.isVariableStatement(n)&&n.declarationList.declarations.some(d=>wanted.includes(d.name.text))).map(n=>n.getText(ast)).join('\n');
let modern={data:null,error:{code:'PGRST205',message:'public.hold_points missing'}};
let legacy={data:[row,{id:'report',project_id:'project-a',title:'פיקוח אמיתי',status:'פתוח'}],error:null};
const context={...helpers.exports,exports:{},HOLD_POINTS_TABLE:'hold_points',SUPERVISION_REPORTS_TABLE:'supervision_reports',normalizeStoredProjectId:x=>x,normalizeAttachments:x=>x||[],selectProjectTable:async(table,order,ids)=>{assert.deepEqual(Array.from(ids),['project-a']);return table==='hold_points'?modern:legacy;}};
vm.runInNewContext(transpile(snippets+'\nexports.test={loadProjectHoldPoints,normalizeSupervisionReport,supervisionReportRowToRecord};'),context);
const api=context.exports.test;
(async()=>{
  assert.equal(api.normalizeSupervisionReport(row),null);
  assert.equal(api.supervisionReportRowToRecord(row),null,'Summary loading and archive conversion must exclude the marker');
  assert.equal(api.supervisionReportRowToRecord(legacy.data[1]).title,'פיקוח אמיתי');
  let loaded=await api.loadProjectHoldPoints(['project-a']);
  assert.equal(loaded.length,1);assert.equal(loaded[0].documents[0].dataUrl,point.documents[0].dataUrl);
  modern={data:[{id:'point',project_id:'project-a',name:'updated',details:{}}],error:null};
  loaded=await api.loadProjectHoldPoints(['project-a']);assert.equal(loaded.length,1);assert.equal(loaded[0].name,'updated','Modern data takes priority without duplicates');
  modern={data:[],error:{code:'42501',message:'permission denied'}};
  await assert.rejects(()=>api.loadProjectHoldPoints(['project-a']));
  console.log('PASS: legacy hold points are excluded from supervision and restored with documents/links; scopes, duplicates, malformed metadata and access errors covered.');
})().catch(e=>{console.error(e);process.exitCode=1;});
