import type { ChecklistItem, ChecklistTemplateDefinition, ChecklistTemplateKey, Project } from './types';
const nowLocal = () => new Date().toLocaleString('he-IL');
export const defaultProjects: Project[] = [{ id: '1', name: 'כביש 781', description: 'פרויקט תשתיות', manager: '', isActive: true, createdAt: nowLocal() }];
export const checklistTemplates: Record<ChecklistTemplateKey, ChecklistTemplateDefinition> = {
  general: { label: 'רשימה כללית', title: 'רשימת תיוג', category: 'עבודות עפר', items: [ { description: 'בדיקת תוכניות לביצוע + מהדורה', responsible: 'בקרת איכות' }, { description: 'בדיקה חזותית לשטח לפני תחילת עבודה', responsible: 'בקרת איכות' }, { description: 'אישור סופי', responsible: 'בקרת איכות' } ] },
  guardrails: { label: 'עבודות מעקות', title: 'רשימת תיוג לעבודות מעקות', category: 'מעקות', items: [ { description: 'אישור המעקה וסוגו', responsible: 'בקרת איכות' }, { description: 'אישור חומרים ובדיקות מוקדמות', responsible: 'בקרת איכות' }, { description: 'אישור סופי', responsible: 'בקרת איכות' } ] },
  aggregateDistribution: { label: 'פיזור מצעים', title: 'רשימת תיוג לעבודות פיזור מצעים', category: 'פיזור מצעים', items: [ { description: 'בדיקות דרגת הידוק ותכולת רטיבות', responsible: 'בקרת איכות' }, { description: 'בדיקת מישוריות', responsible: 'בקרת איכות' }, { description: 'אישור סופי', responsible: 'בקרת איכות' } ] },
  curbstones: { label: 'אבני שפה', title: 'רשימת תיוג לאבני שפה', category: 'אבני שפה', items: [ { description: 'אישור בקרה מוקדמת לטיב החומרים', responsible: 'בקרת איכות' }, { description: 'בדיקת רום שתית', responsible: 'מנהל העבודה' }, { description: 'אישור גמר העבודה', responsible: 'בקרת איכות' } ] },
  standardCompaction: { label: 'הידוק רגיל', title: 'רשימת תיוג לעבודות הידוק רגיל', category: 'הידוק רגיל', items: [ { description: 'בדיקות מעברי מכבש', responsible: 'בקרת איכות' }, { description: 'בדיקת FWD', responsible: 'בקרת איכות' }, { description: 'אישור סופי', responsible: 'בקרת איכות' } ] },
  catsEyes: { label: 'עיני חתול', title: 'רשימת תיוג להתקנת עיני חתול', category: 'התקנת עיני חתול', items: [ { description: 'בקרה מקדימה לחומרים ולציוד', responsible: 'מב"א' }, { description: 'בדיקת נראות', responsible: 'מעבדה' }, { description: 'אישור סופי', responsible: 'מב"א' } ] },
  concreteCasting: { label: 'יציקות באתר', title: 'רשימת תיוג ליציקות באתר', category: 'בטון', items: [ { description: 'אישור ליציקה', responsible: 'מב"א' }, { description: 'נטילת מדגמי בטון', responsible: 'מב"א' }, { description: 'אישור סופי', responsible: 'מב"א' } ] },
  jkWorks: { label: 'עבודות JK', title: 'רשימת תיוג לעבודות JK', category: 'JK', items: [ { description: 'סימון בשטח', responsible: 'מודד' }, { description: 'בדיקת בטון', responsible: 'בקרת איכות' }, { description: 'אישור סופי', responsible: 'בקרת איכות' } ] },
  controlledCompaction: { label: 'הידוק מבוקר', title: 'רשימת תיוג לעבודות הידוק מבוקר', category: 'הידוק מבוקר', items: [ { description: 'בדיקות דרגת הידוק ורטיבות', responsible: 'בקרת איכות' }, { description: 'בדיקת FWD', responsible: 'בקרת איכות' }, { description: 'אישור סופי', responsible: 'בקרת איכות' } ] },
  signage: { label: 'תמרור ושילוט', title: 'רשימת תיוג לעבודות תמרור ושילוט', category: 'תמרור ושילוט', items: [ { description: 'סימון', responsible: 'מודד' }, { description: 'בדיקות החזר אור', responsible: 'בקרת איכות' }, { description: 'אישור הקטע', responsible: 'בקרת איכות' } ] },
  paving: { label: 'ריצוף', title: 'רשימת תיוג עבודות ריצוף', category: 'ריצוף', items: [ { description: 'אישור בקרה מוקדמת לטיב החומרים', responsible: 'בקרת איכות' }, { description: 'בדיקת הידוק ורום מצעים', responsible: 'מנהל העבודה' }, { description: 'אישור גמר העבודה', responsible: 'בקרת איכות' } ] },
  steelGuardrailsSupply: { label: 'אספקה והרכבת מעקות פלדה', title: 'רשימת תיוג לאספקה והרכבת מעקות פלדה', category: 'מעקות פלדה', items: [ { description: 'תעודות הסמכת רתכים', responsible: 'מהנדס בקרת איכות' }, { description: 'בדיקות עובי גילוון', responsible: 'מעבדה' }, { description: 'בדיקת אופן הרכבת המעקה', responsible: 'מהנדס בקרת איכות' } ] },
  asphaltWorks: { label: 'עבודות אספלט', title: 'רשימת תיוג לביצוע עבודות אספלט באתר', category: 'אספלט', items: [ { description: 'אישור בקרה מוקדמת', responsible: 'בקרת איכות' }, { description: 'בדיקות גליות', responsible: 'בקרת איכות' }, { description: 'אישור סופי', responsible: 'בקרת איכות' } ] },
  drainagePiping: { label: 'צנרת ניקוז', title: 'רשימת תיוג התקנת מערכות אספקת מים / צנרת ניקוז', category: 'צנרת ניקוז', items: [ { description: 'סימון צירי החפירה', responsible: 'מודד הקבלן' }, { description: 'בדיקת אטימות וישרות הקו', responsible: 'בקרת איכות' }, { description: 'אישור סופי', responsible: 'בקרת איכות' } ] },
};
export const isChecklistTemplateKey = (value: unknown): value is ChecklistTemplateKey => typeof value === 'string' && value in checklistTemplates;
export const normalizeChecklistTemplateKey = (value: unknown): ChecklistTemplateKey => isChecklistTemplateKey(value) ? value : 'general';
export const buildChecklistItemsFromTemplate = (templateKey: ChecklistTemplateKey): ChecklistItem[] => checklistTemplates[templateKey].items.map((item, index) => ({ id: `${Date.now()}-${index}`, description: item.description, responsible: item.responsible, status: 'לא נבדק', notes: '', inspector: '', executionDate: '' }));
