@echo off
echo Applying build bypass fix...
node scripts\skip-typecheck-build.cjs
echo.
echo Installing dependencies...
npm install
echo.
echo Removing .next cache...
if exist .next rmdir /s /q .next
echo.
echo Running local build...
npm run build
