@echo off
echo Forcing Next.js build to use webpack...
node scripts\force-webpack-build.cjs
echo.
echo Installing dependencies...
npm install
echo.
echo Removing .next cache...
if exist .next rmdir /s /q .next
echo.
echo Running local build...
npm run build
